Fix postgres backup scripts

diff --git a/clusters/building-blocks/persistency/apps/default-postgres/app/default-postgres-backup-cj.yaml b/clusters/building-blocks/persistency/apps/default-postgres/app/default-postgres-backup-cj.yaml
--- a/clusters/building-blocks/persistency/apps/default-postgres/app/default-postgres-backup-cj.yaml
+++ b/clusters/building-blocks/persistency/apps/default-postgres/app/default-postgres-backup-cj.yaml
@@ -16,6 +16,10 @@ spec:
             env:
             - name: TZ
               value: "Europe/Berlin"
+            - name: BACKUP_NAME
+              value: "default-postgres"
+            - name: PROXMOX_BACKUP_SERVER_NAMESPACE
+              value: "k3s/databases"
             envFrom:
             - secretRef:
                 name: default-postgres-backup-secret
@@ -61,27 +65,41 @@ spec:
                 proxmox-backup-client \
                 && rm -rf /var/lib/apt/lists/*
 
+              required_vars=("BACKUP_NAME" "POSTGRES_HOST" "POSTGRES_USER" "POSTGRES_PASSWORD" "PROXMOX_BACKUP_SERVER_PASSWORD" "PROXMOX_BACKUP_SERVER_FINGERPRINT" "PROXMOX_BACKUP_SERVER_REPOSITORY" "TELEGRAM_BOT_TOKEN" "TELEGRAM_CHAT_ID")
+              # Flag to track if all variables are set
+              all_set=true
+              # Check each variable
+              for var in "${required_vars[@]}"; do
+                  if [[ -z "${!var}" ]]; then
+                      echo "Error: Environment variable $var is not set."
+                      all_set=false
+                  fi
+              done
+              # Exit if any variable is not set
+              if [[ "$all_set" == false ]]; then
+                  echo "Please set the required environment variables and try again."
+                  exit 1
+              fi
+
               LOG_FILE=/var/log/backup.log
-              TIMESTAMP=$(date +"%Y%m%d%H%M%S")
-              PBS_BACKUP_NAME="default-postgres.pxar"
               BACKUP_DIRECTORY="/backup"
-              BACKUP_FILE="/backup/default-postgres-backup-$TIMESTAMP.sql"
+              BACKUP_FILE="/backup/postgres-backup.sql"
               echo "Starting Postgres backup to file"
               PGPASSWORD="$POSTGRES_PASSWORD" pg_dumpall -h "$POSTGRES_HOST" -U "$POSTGRES_USER" > "$BACKUP_FILE"
               echo "Postgres successfully backupped to file: $(du -h "$BACKUP_FILE" | cut -f1)"
 
               export PBS_FINGERPRINT=$PROXMOX_BACKUP_SERVER_FINGERPRINT
               export PBS_PASSWORD=$PROXMOX_BACKUP_SERVER_PASSWORD 
-              proxmox-backup-client backup "$PBS_BACKUP_NAME:$BACKUP_DIRECTORY" --repository "$PROXMOX_BACKUP_SERVER_REPOSITORY"
+              proxmox-backup-client backup "$BACKUP_NAME.pxar:$BACKUP_DIRECTORY" --repository "$PROXMOX_BACKUP_SERVER_REPOSITORY" --backup-id $BACKUP_NAME --ns $PROXMOX_BACKUP_SERVER_NAMESPACE
               if [[ $? -ne 0 ]]; then
-                ERROR_MSG="$(date '+%Y-%m-%d %H:%M:%S') - Backup failed for $BACKUP_FILE"
-                send_telegram_message "$ERROR_MSG"
-                echo "$ERROR_MSG"
-                exit 1
+                  ERROR_MSG="$(date '+%Y-%m-%d %H:%M:%S') - Backup failed for $BACKUP_FILE"
+                  send_telegram_message "$ERROR_MSG"
+                  echo "$ERROR_MSG"
+                  exit 1
               else
-                SUCCESS_MSG="$(date '+%Y-%m-%d %H:%M:%S') - Backup for $BACKUP_FILE completed successfully."
-                echo "$SUCCESS_MSG"
-                # send_telegram_message "$SUCCESS_MSG"
+                  SUCCESS_MSG="$(date '+%Y-%m-%d %H:%M:%S') - Backup for $BACKUP_FILE completed successfully."
+                  echo "$SUCCESS_MSG"
+                  # send_telegram_message "$SUCCESS_MSG"
               fi
           restartPolicy: never
           volumes:
